class Event(object):
    PRICE_UPDATE = "PRICE_UPDATE"
    TRANSACTION_EVENT = "TRANSACTION_EVENT"
    TRANSACTION_BUY = "TRANSACTION_BUY"
    TRANSACTION_SELL = "TRANSACTION_SELL"

class Signal(object):
    BUY_SIGNAl = "BUY_SIGNAL"
    SELL_SIGNAL = "SELL_SIGNAL"
    NO_ACTION = "NO_ACTION"
